### PR TITLE
Dist finetune: Enable distributed finetuning

### PR DESCRIPTION
**Pull request by EliasKng**

### CODE REVIEW

**Comment by EliasKng** [comment]
Hey @zhaoshan2, I forekd from your repository, since I am working with Pangu for my own research project, and I really liked your implementation.

To be honest, I didn't mean to create this PR, since the code I've written significantly diverges from your research purpose and might not fit here. (The PR was by accident, Github automatically sets your Repo as origin of PRs, since I've forked from this Repo).

I have no problem with my adaptions being displayed publicly on your repository, however I believe that the code will not be runnable. Therefore it might be worthwile to reset your repo to the state it had before the merge

:)

By the way - great work, your pangu model works great!

By any chance: Do you also have pretrained model weights for the other pangu models (e.g., the 6h or 1h models)?

Thanks

**Comment by zhaoshan2** [comment]
Hi @EliasKng Thank you for your interest. So far, I haven’t converted the ONNX weights to Torch weights for the 6-hour and 1-hour models, but I assume the process would be quite similar. The conversion involves aligning the keys between the ONNX files and the Pangu (PyTorch version) models [onnx2torch.py](https://github.com/zhaoshan2/pangu-pytorch/blob/97db96bc9c039cd7fd3e3330bcd3b536c8b446cf/models/onnx2torch.py).

I've uploaded the lookup table for the 24-hour version [keys_all.csv](https://github.com/zhaoshan2/pangu-pytorch/blob/97db96bc9c039cd7fd3e3330bcd3b536c8b446cf/keys_all.csv) . There might be slight differences in key names, but I expect only minor changes.

**Comment by EliasKng** [comment]
@zhaoshan2 Great, thanks for uploading the keys! I'll look into it and try to convert the other onnx models, too. Thanks

... it must have been a tedious process to patch all those keys, right?

**Comment by zhaoshan2** [comment]
@EliasKng incredibly tedious process to manually pair them...

**Pull request merged**
